# Generated by Django 3.0.6 on 2020-07-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('head1', models.CharField(default='', max_length=100)),
                ('chead1', models.TextField(default='')),
                ('head2', models.CharField(default='', max_length=100)),
                ('chead2', models.TextField(default='')),
                ('head3', models.CharField(default='', max_length=100)),
                ('chead3', models.TextField(default='')),
                ('pub_date', models.DateField()),
                ('img', models.ImageField(upload_to='blog/images')),
            ],
        ),
    ]
